# Generated by Django 4.1.7 on 2023-06-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrologer',
            name='year_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
