# Generated by Django 4.1.7 on 2023-05-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_astrologerprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrologerprofile',
            name='year_of_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
