# Generated by Django 4.1.7 on 2023-05-13 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='translated_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='customer',
            field=models.ForeignKey(default = 1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
            preserve_default=False,
        ),
    ]
